version: "3"
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    depends_on:
      - mysql
    ports:
      - "3000:3000"
    container_name: frontend-nextjs
    volumes:
      - ./frontend:/usr/src/app/frontend
    command: npm run dev
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      - mysql
    ports:
      - "5000:5000"
    container_name: backend-flask
    volumes:
      - ./backend:/usr/src/app/backend
    command: >
      bash -c '
      flask run --host=0.0.0.0'
  mysql:
    image: mysql:8.0
    volumes:
      - ./mysql/etc/my.cnf:/etc/my.cnf
    container_name: db-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=database
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    ports:
      - 3305:3305
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --default_authentication_plugin=mysql_native_password